### ISSUE TITLE
Enhancement: Bot Support

### ISSUE THREAD

**Issue by TomMD** [glguy/Ninjas#6]
I'm building bot support and DSL to help teach my nieces, nephews, and daughters to program.  I'd like to make sure what I build can get upstream.

1. Add "Ninjas bot" support via a module Bot.hs.  This module includes "runBot" which either uses a default bot or loads some bytecode from a file specified at runtime.

2.  Define a turning-complete byte code.  No strong ideas here yet, but basic operations of Move, Attack, Smoke, and GetWorld would be included.

3. Define a language 'Ninja'.  This could be a "typical" DSL that includes the primitives and helper functions in the style of: 

    distanceTo :: World -> Entity -> Int              -- returns the distance to the taget
    followBeizer :: World -> Entity -> Command  -- returns a Move command

  Or it could be a more restrictive language that takes a set of conditions for attacking, moving, and smoking.  In this case the possible "conditions" and their logical connectives would be part of the language.

4. Make a stand-alone compiler, shipped with Ninjas, that compiles Ninja to NBC - Ninja to Ninja bytecode.  Also, write tutorials.

5. Parameterize the step rate in the server to allow faster game play for tournaments or faster evolution of Ninjas (given a genetic algorithm).

6. Add a server parameter that will identify the clients' Ninja, allowing easier development.

**Comment by glguy** [comment]
merged!
